# Generated by Django 4.1.3 on 2022-11-17 20:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('folder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500, validators=[django.core.validators.URLValidator(schemes=('http', 'https'))], verbose_name='リンク')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IPアドレス')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder.folder', verbose_name='フォルダ')),
            ],
        ),
    ]
